/* eslint-disable */
// WARNING DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_appsync_graphqlEndpoint": "https://tk6tovel6ff5ja6qp3wrd3qjhq.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-og74ulwhgnc45pusnrih6lqdbe",
    "aws_cognito_identity_pool_id": "us-east-2:2275f7bf-deeb-4682-a025-a2820e040f1b",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_FupEfzW6A",
    "aws_user_pools_web_client_id": "3n28bjml2rt3ekmgporqmgpsoq",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
